### ISSUE TITLE
Not taking into account padding

### ISSUE THREAD

**Issue by LingoSam** [jsliang/eqHeight.coffee#15]
I have two columns that I am attempting to make the same height.
Script is working but is not taking into account that one of the columns has different padding.

I am no coder, but I think changing the instances of .height to .outerHeight resolves the issue...

**Comment by jsliang** [comment]
Hi @LingoSam , could you provide an example, probably using http://jsfiddle.net/? tks

**Comment by jsliang** [comment]
Hi, I believe #17 has fixed this problem. If that doesn't, feel free to reopen this issue. Thanks. :)

**Comment by florushj** [comment]
This issue is not fixed yet. See this [jsfiddle](http://jsfiddle.net/yd78jfuv/). What is does is take the height of the column and add up the padding to this height. (try changing the padding to 0 and see the difference). I would like to have the height including the padding. 

In the js file this could be fixed by changing line 40: 

``` javascript
marked_columns.height(max_col_height);
```

to 

``` javascript
marked_columns.outerHeight(max_col_height);
```

**Comment by Propaganistas** [comment]
I can confirm that this issue is not fixed without applying the suggestion of @florushj .
