### ISSUE TITLE
Multiple row resizing

### ISSUE THREAD

**Issue by FernE97** [jsliang/eqHeight.coffee#8]
I'm having an issue when there is more than one row. The first row stays the same height as it's tallest div when the page was loaded but the second row still calculates the height when resizing the window. If I just have one row it works perfectly. I created a jsfiddle to show the issue http://jsfiddle.net/ferne97/KHmdr/6/. Thanks, nice plugin by the way.

**Comment by jsliang** [comment]
I was occupied with my personal matters and wasn't able to look at this bug. I finally have the chance to look at it today, but haven't been able to figure out what causes this issue so far...:(
Still working on it now.

**Comment by FernE97** [comment]
Thanks, let me know if there is anything I can do to help.

**Comment by carasmo** [comment]
Is this issue resolved? The problem went away with the use of the interval option. I also made sure the rows cleared. Hell if I know what happened but it's gone now. Thanks for this GREAT script!

**Comment by jsliang** [comment]
Hi @carasmo , thank you for your feedback!
I don't think this issue is resolved though. By replacing @FernE97's jsfiddle with the latest jquery.eqheight.js (v1.2.8), the issue still presents: http://jsfiddle.net/KHmdr/7/
I feel sorry that I've been occupied with my personal affairs these months and haven't got time to look into it. :(

**Comment by carasmo** [comment]
I did get it to work, but I ended up using something else.

http://jsbin.com/uBeQERiJ/6/
